openapi: 3.0.3
info:
  title: Developer Portfolio API
  version: 1.0.0
  description: API for managing portfolio projects, including CRUD operations and
    file uploads.
paths:
  /api/projects/:
    get:
      operationId: api_projects_list
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      tags:
      - api
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
          description: ''
    post:
      operationId: api_projects_create
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
  /api/projects/{id}/:
    get:
      operationId: api_projects_retrieve
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    put:
      operationId: api_projects_update
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    patch:
      operationId: api_projects_partial_update
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProject'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProject'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
          description: ''
    delete:
      operationId: api_projects_destroy
      description: |-
        API endpoints for managing projects.

        - GET /api/projects/: List all projects (public).
        - GET /api/projects/<id>/: Retrieve a project (public).
        - POST /api/projects/: Create a project (admin only).
        - PUT/PATCH /api/projects/<id>/: Update a project (admin only).
        - DELETE /api/projects/<id>/: Delete a project (admin only).
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this project.
        required: true
      tags:
      - api
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - tokenAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    PatchedProject:
      type: object
      description: Serializer for Project model, handling project data and image uploads.
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        technologies:
          type: string
          maxLength: 200
        image:
          type: string
          format: uri
          nullable: true
        project_url:
          type: string
          format: uri
          maxLength: 200
        repository_url:
          type: string
          format: uri
          maxLength: 200
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    Project:
      type: object
      description: Serializer for Project model, handling project data and image uploads.
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        technologies:
          type: string
          maxLength: 200
        image:
          type: string
          format: uri
          nullable: true
        project_url:
          type: string
          format: uri
          maxLength: 200
        repository_url:
          type: string
          format: uri
          maxLength: 200
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - description
      - id
      - title
      - updated_at
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
