# Generated by Django 5.2.1 on 2025-05-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='reviewer_title',
            field=models.CharField(max_length=100),
        ),
    ]
